version: "3"
services:
  app:
    build:
      context: ./app
    volumes:
      - ./..:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      APP_ADMINISTRATOR_TEAM_ID: "22105"
      APP_CONSOLE_URL: "http://web.monitoring.sunfox.localhost/"
      APP_DBAL_CONNECTION_TZ: "+02:00"
      APP_DBAL_DATABASE: "monitoring"
      APP_DBAL_HOST: "db"
      APP_DBAL_PASSWORD: "monitoring"
      APP_DBAL_USERNAME: "monitoring"
      APP_GITHUB_APP_ID: "Iv1.3846d354aa7dfcd8"
      APP_GITHUB_APP_SECRET: "87f4639638c8fcaeabf3751c2da0837678061fb1"
      APP_RABBITMQ_HOST: "rabbitmq"
      APP_RABBITMQ_PASSWORD: "monitoring"
      APP_RABBITMQ_PORT: "5672"
      APP_RABBITMQ_USER: "monitoring"
      APP_RABBITMQ_VHOST: "monitoring"
      APP_SLACK_HOOK_URL: ""
    networks:
      - monitoring

  cron:
    build:
      context: ./cron
    volumes:
      - ./..:/var/www/html
    restart: always
    networks:
      - monitoring

  db:
    image: mysql:5.7
    volumes:
      - ./data/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: foo
      MYSQL_DATABASE: monitoring
      MYSQL_USER: monitoring
      MYSQL_PASSWORD: monitoring
    networks:
      - monitoring

  rabbitmq:
    build:
      context: ./rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: monitoring
      RABBITMQ_DEFAULT_PASS: monitoring
      RABBITMQ_DEFAULT_VHOST: monitoring
    networks:
      - monitoring

  adminer:
    image: adminer
    ports:
      - 81:8080
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge